repos:
  # Lint and format Python code with Ruff.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.2
    hooks:
      - id: ruff-check
        args: [--fix]
      - id: ruff-format
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
  # Lint and format TypeScript code with ESLint.
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        types_or: [jsx, tsx, ts, css, json, html]
  # Check project typing.
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.19.1
    hooks:
      - id: mypy
        additional_dependencies: [
          "fastapi",
          "pydantic",
          "pymongo"
        ]
        args: [--config-file=pyproject.toml]
  # Validate commit messages.
  - repo: local
    hooks:
      - id: check-commit-message
        name: Validate & Format Commit Message
        entry: python3 scripts/check_commit_message.py
        language: python
        stages: [commit-msg]
  # Test application.
  - repo: local
    hooks:
      - id: application-tests-coverage
        name: Run Application Tests with Coverage
        entry: bash ai-annotator.sh -t
        language: system
        always_run: true
        verbose: true
        pass_filenames: false
        stages: [pre-push]
