services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ai_annotator_db
    ports:
      - "27017:27017"
    volumes:
      - ${LOCAL_STORAGE_PATH}/mongodb:/data/db
    command: ["mongod", "--quiet", "--logpath", "/dev/null"]
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: production
    container_name: ai_annotator_backend
    ports:
      - "8000:8000"
    volumes:
      - ${LOCAL_STORAGE_PATH}/static:/app/storage
    depends_on:
      - database
    profiles:
      - app
  backend-tests:
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: testing
    container_name: ai_annotator_backend_tests
    volumes:
      - ${LOCAL_STORAGE_PATH}/static:/app/storage
    depends_on:
      - database
    environment:
      - AI_ANNOTATOR_DATABASE_NAME=ai_annotator_db_test
    profiles:
      - unittest