# Base image.
FROM python:3.12-slim
# Install system dependencies.
COPY ./backend/requirements.txt /tmp
RUN pip install --no-cache-dir -r /tmp/requirements.txt
# Set working directory.
WORKDIR /home
# Copy application code.
COPY ./backend ./backend
# Expose the application port.
EXPOSE 8000
# Run the application.
ENV PYTHONPATH=/home
ENTRYPOINT [ "python", "/home/backend/app.py" ]