services:
  database:
    build:
      context: .
      dockerfile: Dockerfile.db
    container_name: ai_annotator_db
    ports:
      - "27017:27017"
    volumes:
      - ${LOCAL_STORAGE_PATH}/mongodb:/data/db
  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: ai_annotator_backend
    ports:
      - "8000:8000"
    volumes:
      - ${LOCAL_STORAGE_PATH}/static:/app/storage
    depends_on:
      - database